services:
  vulnbox1:
    container_name: vulnbox1
    build: ./vulnbox
    privileged: true
    networks:
      cyber_network:
        ipv4_address: 10.60.1.1
    volumes:
      - /var/lib/docker/overlay2:/var/lib/docker/overlay2
      - /var/lib/docker/image/overlay2:/var/lib/docker/image/overlay2
    dns:                # Unipa ready
      - 10.80.150.1     # Unipa ready
  vulnbox2:
    container_name: vulnbox2
    build: ./vulnbox
    privileged: true
    networks:
      cyber_network:
        ipv4_address: 10.60.2.1
    volumes:
      - /var/lib/docker/overlay2:/var/lib/docker/overlay2
      - /var/lib/docker/image/overlay2:/var/lib/docker/image/overlay2
    dns:                # Unipa ready
      - 10.80.150.1     # Unipa ready
  vulnbox3:
    container_name: vulnbox3
    build: ./vulnbox
    privileged: true
    networks:
      cyber_network:
        ipv4_address: 10.60.3.1
    volumes:
      - /var/lib/docker/overlay2:/var/lib/docker/overlay2
      - /var/lib/docker/image/overlay2:/var/lib/docker/image/overlay2
    dns:                # Unipa ready
      - 10.80.150.1     # Unipa ready
  vulnbox4:
    container_name: vulnbox4
    build: ./vulnbox
    privileged: true
    networks:
      cyber_network:
        ipv4_address: 10.60.4.1
    volumes:
      - /var/lib/docker/overlay2:/var/lib/docker/overlay2
      - /var/lib/docker/image/overlay2:/var/lib/docker/image/overlay2
    dns:                # Unipa ready
      - 10.80.150.1     # Unipa ready
  vulnbox5:
    container_name: vulnbox5
    build: ./vulnbox
    privileged: true
    networks:
      cyber_network:
        ipv4_address: 10.60.5.1
    volumes:
      - /var/lib/docker/overlay2:/var/lib/docker/overlay2
      - /var/lib/docker/image/overlay2:/var/lib/docker/image/overlay2
    dns:                # Unipa ready
      - 10.80.150.1     # Unipa ready
  vulnbox6:
    container_name: vulnbox6
    build: ./vulnbox
    privileged: true
    networks:
      cyber_network:
        ipv4_address: 10.60.6.1
    volumes:
      - /var/lib/docker/overlay2:/var/lib/docker/overlay2
      - /var/lib/docker/image/overlay2:/var/lib/docker/image/overlay2
    dns:                # Unipa ready
      - 10.80.150.1     # Unipa ready
  vulnbox7:
    container_name: vulnbox7
    build: ./vulnbox
    privileged: true
    networks:
      cyber_network:
        ipv4_address: 10.60.7.1
    volumes:
      - /var/lib/docker/overlay2:/var/lib/docker/overlay2
      - /var/lib/docker/image/overlay2:/var/lib/docker/image/overlay2
    dns:                # Unipa ready
      - 10.80.150.1     # Unipa ready
  vulnbox8:
    container_name: vulnbox8
    build: ./vulnbox
    privileged: true
    networks:
      cyber_network:
        ipv4_address: 10.60.8.1
    volumes:
      - /var/lib/docker/overlay2:/var/lib/docker/overlay2
      - /var/lib/docker/image/overlay2:/var/lib/docker/image/overlay2
    dns:                # Unipa ready
      - 10.80.150.1     # Unipa ready
  vulnbox9:
    container_name: vulnbox9
    build: ./vulnbox
    privileged: true
    networks:
      cyber_network:
        ipv4_address: 10.60.9.1
    volumes:
      - /var/lib/docker/overlay2:/var/lib/docker/overlay2
      - /var/lib/docker/image/overlay2:/var/lib/docker/image/overlay2
    dns:                # Unipa ready
      - 10.80.150.1     # Unipa ready
  vulnbox10:
    container_name: vulnbox10
    build: ./vulnbox
    privileged: true
    networks:
      cyber_network:
        ipv4_address: 10.60.10.1
    volumes:
      - /var/lib/docker/overlay2:/var/lib/docker/overlay2
      - /var/lib/docker/image/overlay2:/var/lib/docker/image/overlay2
    dns:                # Unipa ready
      - 10.80.150.1     # Unipa ready
  vulnbox11:
    container_name: vulnbox11
    build: ./vulnbox
    privileged: true
    networks:
      cyber_network:
        ipv4_address: 10.60.11.1
    volumes:
      - /var/lib/docker/overlay2:/var/lib/docker/overlay2
      - /var/lib/docker/image/overlay2:/var/lib/docker/image/overlay2
    dns:                # Unipa ready
      - 10.80.150.1     # Unipa ready
  vulnbox12:
    container_name: vulnbox12
    build: ./vulnbox
    privileged: true
    networks:
      cyber_network:
        ipv4_address: 10.60.12.1
    volumes:
      - /var/lib/docker/overlay2:/var/lib/docker/overlay2
      - /var/lib/docker/image/overlay2:/var/lib/docker/image/overlay2
    dns:                # Unipa ready
      - 10.80.150.1     # Unipa ready
  vulnbox13:
    container_name: vulnbox13
    build: ./vulnbox
    privileged: true
    networks:
      cyber_network:
        ipv4_address: 10.60.13.1
    volumes:
      - /var/lib/docker/overlay2:/var/lib/docker/overlay2
      - /var/lib/docker/image/overlay2:/var/lib/docker/image/overlay2
    dns:                # Unipa ready
      - 10.80.150.1     # Unipa ready
  vulnbox14:
    container_name: vulnbox14
    build: ./vulnbox
    privileged: true
    networks:
      cyber_network:
        ipv4_address: 10.60.14.1
    volumes:
      - /var/lib/docker/overlay2:/var/lib/docker/overlay2
      - /var/lib/docker/image/overlay2:/var/lib/docker/image/overlay2
    dns:                # Unipa ready
      - 10.80.150.1     # Unipa ready
  vulnbox15:
    container_name: vulnbox15
    build: ./vulnbox
    privileged: true
    networks:
      cyber_network:
        ipv4_address: 10.60.15.1
    volumes:
      - /var/lib/docker/overlay2:/var/lib/docker/overlay2
      - /var/lib/docker/image/overlay2:/var/lib/docker/image/overlay2
    dns:                # Unipa ready
      - 10.80.150.1     # Unipa ready
  vulnbox16:
    container_name: vulnbox16
    build: ./vulnbox
    privileged: true
    networks:
      cyber_network:
        ipv4_address: 10.60.16.1
    volumes:
      - /var/lib/docker/overlay2:/var/lib/docker/overlay2
      - /var/lib/docker/image/overlay2:/var/lib/docker/image/overlay2
    dns:                # Unipa ready
      - 10.80.150.1     # Unipa ready
  vulnbox17:
    container_name: vulnbox17
    build: ./vulnbox
    privileged: true
    networks:
      cyber_network:
        ipv4_address: 10.60.17.1
    volumes:
      - /var/lib/docker/overlay2:/var/lib/docker/overlay2
      - /var/lib/docker/image/overlay2:/var/lib/docker/image/overlay2
    dns:                # Unipa ready
      - 10.80.150.1     # Unipa ready
  vulnbox18:
    container_name: vulnbox18
    build: ./vulnbox
    privileged: true
    networks:
      cyber_network:
        ipv4_address: 10.60.18.1
    volumes:
      - /var/lib/docker/overlay2:/var/lib/docker/overlay2
      - /var/lib/docker/image/overlay2:/var/lib/docker/image/overlay2
    dns:                # Unipa ready
      - 10.80.150.1     # Unipa ready
  vulnbox19:
    container_name: vulnbox19
    build: ./vulnbox
    privileged: true
    networks:
      cyber_network:
        ipv4_address: 10.60.19.1
    volumes:
      - /var/lib/docker/overlay2:/var/lib/docker/overlay2
      - /var/lib/docker/image/overlay2:/var/lib/docker/image/overlay2
    dns:                # Unipa ready
      - 10.80.150.1     # Unipa ready
  vulnbox20:
    container_name: vulnbox20
    build: ./vulnbox
    privileged: true
    networks:
      cyber_network:
        ipv4_address: 10.60.20.1
    volumes:
      - /var/lib/docker/overlay2:/var/lib/docker/overlay2
      - /var/lib/docker/image/overlay2:/var/lib/docker/image/overlay2
    dns:                # Unipa ready
      - 10.80.150.1     # Unipa ready
  vulnbox21:
    container_name: vulnbox21
    build: ./vulnbox
    privileged: true
    networks:
      cyber_network:
        ipv4_address: 10.60.21.1
    volumes:
      - /var/lib/docker/overlay2:/var/lib/docker/overlay2
      - /var/lib/docker/image/overlay2:/var/lib/docker/image/overlay2
    dns:                # Unipa ready
      - 10.80.150.1     # Unipa ready
  vulnbox22:
    container_name: vulnbox22
    build: ./vulnbox
    privileged: true
    networks:
      cyber_network:
        ipv4_address: 10.60.22.1
    volumes:
      - /var/lib/docker/overlay2:/var/lib/docker/overlay2
      - /var/lib/docker/image/overlay2:/var/lib/docker/image/overlay2
    dns:                # Unipa ready
      - 10.80.150.1     # Unipa ready
  vulnbox23:
    container_name: vulnbox23
    build: ./vulnbox
    privileged: true
    networks:
      cyber_network:
        ipv4_address: 10.60.23.1
    volumes:
      - /var/lib/docker/overlay2:/var/lib/docker/overlay2
      - /var/lib/docker/image/overlay2:/var/lib/docker/image/overlay2
    dns:                # Unipa ready
      - 10.80.150.1     # Unipa ready
  vulnbox24:
    container_name: vulnbox24
    build: ./vulnbox
    privileged: true
    networks:
      cyber_network:
        ipv4_address: 10.60.24.1
    volumes:
      - /var/lib/docker/overlay2:/var/lib/docker/overlay2
      - /var/lib/docker/image/overlay2:/var/lib/docker/image/overlay2
    dns:                # Unipa ready
      - 10.80.150.1     # Unipa ready
  vulnbox25:
    container_name: vulnbox25
    build: ./vulnbox
    privileged: true
    networks:
      cyber_network:
        ipv4_address: 10.60.25.1
    volumes:
      - /var/lib/docker/overlay2:/var/lib/docker/overlay2
      - /var/lib/docker/image/overlay2:/var/lib/docker/image/overlay2
    dns:                # Unipa ready
      - 10.80.150.1     # Unipa ready

networks:
  cyber_network:
    name: cyber_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.60.0.0/16
    driver_opts:
      com.docker.network.bridge.name: cyber_network
